# Generated by Django 4.1.4 on 2022-12-10 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0002_path'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Path',
            new_name='Route',
        ),
        migrations.RemoveField(
            model_name='route',
            name='userProfile',
        ),
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
